apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "appointment-service.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "appointment-service.labels" . | nindent 4 }}
data:
  DB_HOST: {{ .Values.env.DB_HOST | quote }}
  DB_PORT: {{ .Values.env.DB_PORT | quote }}
  DB_DATABASE: {{ .Values.env.DB_DATABASE | quote }}
  DB_USERNAME: {{ .Values.env.DB_USERNAME | quote }}
  KAFKA_BROKER: {{ .Values.env.KAFKA_BROKER | quote }}
  RABBITMQ_HOST: {{ .Values.env.RABBITMQ_HOST | quote }}
  RABBITMQ_PORT: {{ .Values.env.RABBITMQ_PORT | quote }}
  RABBITMQ_USERNAME: {{ .Values.env.RABBITMQ_USERNAME | quote }}
