apiVersion: v1
kind: Secret
metadata:
  name: {{ include "appointment-service.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "appointment-service.labels" . | nindent 4 }}
type: Opaque
data:
  DB_PASSWORD: {{ .Values.secrets.DB_PASSWORD | b64enc | quote }}
  RABBITMQ_PASSWORD: {{ .Values.secrets.RABBITMQ_PASSWORD | b64enc | quote }}
