# ── Auth Service – DEV Values ──

replicaCount: 1

service:
  type: NodePort
  port: 8083
  targetPort: 8083
  nodePort: 30004

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 250m
    memory: 512Mi

env:
  DB_HOST: medtrust-postgres
  DB_PORT: "5432"
  DB_DATABASE: medtrust
  DB_USERNAME: medtrust
  KAFKA_BROKER: medtrust-kafka:9092
  SPRING_PROFILES_ACTIVE: dev

secrets:
  DB_PASSWORD: dev-changeme
  JWT_SECRET: dev-medtrust-jwt-secret-key-that-is-at-least-256-bits-long-for-hs256

nodeSelector:
  workload: services

podAntiAffinity: false
