apiVersion: v1
kind: Secret
metadata:
  name: {{ include "audit-service.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels: {{- include "audit-service.labels" . | nindent 4 }}
type: Opaque
data:
  DB_PASSWORD: {{ .Values.secrets.DB_PASSWORD | b64enc | quote }}
