version: '3.8'

services:
  medtrust-db:
    image: postgres:16-alpine
    container_name: medtrust-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: medtrust
      POSTGRES_PASSWORD: changeme
    volumes:
      - medtrust_db_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U medtrust -d postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: medtrust
      RABBITMQ_DEFAULT_PASS: changeme
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  medtrust_db_data:
